In [3]:
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_csv('C:/Users/ksa/Documents/Machine Learning A-Z/Machine Learning A-Z/Machine Learning A-Z New/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Churn_Modelling.csv')

In [9]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [37]:
X = dataset.drop('Exited', axis = 1)
Y = dataset[['Exited']]
X.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  
0        101348.88  
1        112542.58  
2        113931.57  
3         93826.63  
4         79084.10

In [43]:
X_1 = pd.get_dummies(X, columns = ['Geography', 'Gender'])
X_1.drop(['Surname', 'RowNumber'],  axis = 1, inplace = True)
X_1.head()

CustomerId  CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0    15634602          619   42       2       0.00              1          1   
1    15647311          608   41       1   83807.86              1          0   
2    15619304          502   42       8  159660.80              3          1   
3    15701354          699   39       1       0.00              2          0   
4    15737888          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88                 1                  0   
1               1        112542.58                 0                  0   
2               0        113931.57                 1                  0   
3               0         93826.63                 1                  0   
4               1         79084.10                 0                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                1              1            0  
2                0              1            0  
3                0              1            0  
4                1              1            0

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(X_1,Y, test_size =.30, random_state = 0)

In [115]:
X_test.head()

CustomerId  CreditScore  Age  Tenure    Balance  NumOfProducts  \
9394    15615753          597   35       8  131101.04              1   
898     15654700          523   40       2  102967.41              1   
2398    15633877          706   42       8   95386.82              1   
5906    15745623          788   32       4  112079.58              1   
2343    15765902          706   38       5  163034.82              2   

      HasCrCard  IsActiveMember  EstimatedSalary  Geography_France  \
9394          1               1        192852.67                 0   
898           1               0        128702.10                 1   
2398          1               1         75732.25                 0   
5906          0               0         89368.59                 1   
2343          1               1        135662.17                 0   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
9394                  1                0              1            0  
898                   0                0              1            0  
2398                  0                1              1            0  
5906                  0                0              0            1  
2343                  1                0              0            1

In [135]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

## Run Logistic Regression to compare with ANN

In [101]:
from sklearn.linear_model import LogisticRegression
Logreg = LogisticRegression(random_state = 0)
Logreg.fit(X_train, Y_train)
predictions = Logreg.predict(X_test)


C:\Users\ksa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [140]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [134]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, predictions)

array([[2282,   97],
       [ 480,  141]], dtype=int64)

## Artificial Neural Network

In [118]:
import keras
# Initialize Neural network
from keras.models import Sequential
# Create layers in ANN
from keras.layers import Dense

In [119]:
#intialize Neural Network
classifier = Sequential()

In [120]:
# Adding Input and first hidden layer
# Output_dim = hidden layer (random), init = weight assignment, activation = activation function, input_dim = input nodes/featues 
classifier.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 14))

#Adding the second Hidden Layer
classifier.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))

#Adding the Output Layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

#Add Compiler (Stochastic Gradient Descent - 'ADAM')
classifier.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'] )

C:\Users\ksa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=14, units=8, kernel_initializer="uniform")`
  
C:\Users\ksa\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  """
C:\Users\ksa\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [138]:
# Fit the ANN model to training set
classifier.fit(X_train, Y_train, batch_size = 10, nb_epoch = 50)

Epoch 1/50
1230/7000 [====>.........................] - ETA: 0s - loss: 0.4277 - accuracy: 0.8138

C:\Users\ksa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


7000/7000 [==============================] - 1s 119us/step - loss: 0.3974 - accuracy: 0.8361
Epoch 2/50
7000/7000 [==============================] - 1s 117us/step - loss: 0.3981 - accuracy: 0.8360
Epoch 3/50
7000/7000 [==============================] - 1s 122us/step - loss: 0.3975 - accuracy: 0.8374
Epoch 4/50
7000/7000 [==============================] - 1s 118us/step - loss: 0.3975 - accuracy: 0.8364
Epoch 5/50
7000/7000 [==============================] - 1s 117us/step - loss: 0.3977 - accuracy: 0.8363
Epoch 6/50
7000/7000 [==============================] - 1s 118us/step - loss: 0.3975 - accuracy: 0.8354
Epoch 7/50
7000/7000 [==============================] - 1s 113us/step - loss: 0.3974 - accuracy: 0.8354
Epoch 8/50
7000/7000 [==============================] - 1s 119us/step - loss: 0.3978 - accuracy: 0.8353
Epoch 9/50
7000/7000 [==============================] - 1s 117us/step - loss: 0.3970 - accuracy: 0.8356
Epoch 10/50
7000/7000 [==============================] - 1s 111us/step - lo

In [142]:
# Evaluate the ANN model on test
ANN_Predict = classifier.predict(X_test)

ANN_Predict

array([[0.18400615],
       [0.36117652],
       [0.14854631],
       ...,
       [0.11095265],
       [0.06768301],
       [0.4978975 ]], dtype=float32)

In [144]:
# Change the probabilities to binary True Or False to run the model accuracy
ANN_Predict = (ANN_Predict> 0.5)
ANN_Predict

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [145]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, ANN_Predict)

array([[2315,   64],
       [ 407,  214]], dtype=int64)